-- Run this in your Supabase SQL Editor
-- Updated schema with chain and token_address support

create table monitors (
  id bigint generated by default as identity primary key,
  chat_id text not null,
  address text not null,
  chain text default 'aptos' not null,
  token_address text,
  threshold float default 10,
  name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(chat_id, address, chain, token_address)
);

-- Optional: Enable Row Level Security (RLS) if you want to restrict access
-- For a bot where the server key is used, RLS is often bypassed by the service_role key anyway,
-- but good practice if you expose this via a frontend later.
alter table monitors enable row level security;

create policy "Enable read access for all users" on monitors for select using (true);
create policy "Enable insert for all users" on monitors for insert with check (true);
create policy "Enable delete for all users" on monitors for delete using (true);

-- Migration: Add last_alerted_at column
-- Run this if you already have the table created
-- alter table monitors add column last_alerted_at timestamp with time zone;
